---
name: Deploy Website with Surge

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Job_Deploy_Surge
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2-beta
              with:
                node-version: '12'
            - name: Setup Surge
              run: npm install --global surge
            - name: Execute Deployement With Surge
              run: surge ./ Bootcamp-2020-project001_AshadBK.surge.sh --token ${{ secrets.Bootcamp-2020-project001_surge_token}}
              
...